/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 parfum_bottle.gltf 
Author: AT design studio (https://sketchfab.com/ANDRIANIAINAToky)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/parfum-bottle-eb42a7f2b2c14af1b1908d15eac175a2
Title: Parfum Bottle
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/parfum_bottle.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bottle_1_Realistic_Glass_0.geometry} material={materials.Realistic_Glass} />
          <mesh geometry={nodes.Circle001_Realistic_Glass_0.geometry} material={materials.Realistic_Glass} position={[0, 0, 2.477]} />
          <mesh geometry={nodes.Liquid_Realistic_Glass001_0.geometry} material={materials['Realistic_Glass.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/parfum_bottle.gltf')
